### ISSUE TITLE
wm 命令设置分辨率和密度

### ISSUE THREAD

**Issue by hqw700** [mzlogin/awesome-adb#11]
楼主提了adb shell wm 查看当前的分辨率和密度，居然没提设置，超级有用的一条命令。
adb shell wm size 480x854 临时设置屏幕尺寸
adb shell wm density 200 临时设置屏幕密度
adb shell wm overscan 0,200,100,0  缩小屏幕
恢复默认用 reset 参数

**Comment by mzlogin** [comment]
@hqw700 感谢提醒，我后来整理一下补充进去，多谢！

**Comment by hqw700** [comment]
客气了。还有就是settings命令也是提的简单了点。
settings 命令带查询，修改和删除settings.db数据的功能。
而且！ user 版本也可以用。
adb shell settings get global wifi_on
adb shell settings delete global wifi_on
adb shell settings put global stay_on_while_plugged_in 3   //打开插上usb屏幕常亮

**Comment by mzlogin** [comment]
@hqw700 确实如此。settings 这块我之前的考虑是觉得可能可以做的事情也不少，然后打算单独开一个章节来讲的，结果一直没弄。请问你对此的了解主要是通过哪些资料呢？

**Comment by hqw700** [comment]
没什么资料，只是那天有空把 frameworks\base\cmds 下的命令一个个试了遍

**Comment by mzlogin** [comment]
哈哈哈哈 直接去源码里找的么，厉害啊！我后来整理的时候也去瞅瞅~

**Comment by OYLL123** [comment]
您好，看了你网页上的教程，有个关于在pixel 4上刷入Android11 kernel的问题想请教您，如果你有空的话，可以邮件联系我一下吗1298140258@qq.com？

**Comment by hqw700** [comment]
您好，
麻烦描述下问题，因为我本身没有研究kernel的需求，当时花了一下午尝试了下，并没有成功，所以不确定能不能帮到你




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "mzlogin/awesome-adb"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Aug 6, 2021 02:43 PM
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
Subject:&nbsp;Re: [mzlogin/awesome-adb] wm 命令设置分辨率和密度 (#11)





 
您好，看了你网页上的教程，有个关于在pixel 4上刷入Android11 ***@***.***？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
