### ISSUE TITLE
adb forward也可以介绍一下哦

### ISSUE THREAD

**Issue by smuwjs** [mzlogin/awesome-adb#12]
adb forward也可以介绍一下哦

**Comment by mzlogin** [comment]
@smuwjs 这个可以有~有什么经典和常用的用法列举和推荐吗？ 😄

**Comment by smuwjs** [comment]
阅读了你整理的，整理得很好啊，发现没有adb forward，就这几条命令呀
![adb forward](https://cloud.githubusercontent.com/assets/12137473/18979763/6ffe7228-8700-11e6-8bef-17bc87767f8f.png)
