### ISSUE TITLE
INSTALL_FAILED_UPDATE_INCOMPATIBLE解决方案

### ISSUE THREAD

**Issue by zxning** [mzlogin/awesome-adb#15]
在手机端使用系统自带的卸载功能卸载某app后，再使用adb命令进行安装，弹出以下错误：
INSTALL_FAILED_UPDATE_INCOMPATIBLE或者INSTALL_FAILED_ALREADY_EXISTS。

可以这样解决：
adb uninstall packagename

然后再安装

**Comment by mzlogin** [comment]
已经整理补充进文档了，thx！
