### ISSUE TITLE
日志级别过滤应该是这样

### ISSUE THREAD

**Issue by wswenyue** [mzlogin/awesome-adb#24]
日志级别过滤应该是这样：
adb logcat "*:W"

不加双引号会报错

**Comment by mzlogin** [comment]
我猜你应该是使用 macOS？我试了一下，在 Mac 下不加双引号确实会报错。

在 Windows 下不加双引号是正常的，官方文档举例也没加双引号。<https://developer.android.com/studio/command-line/logcat.html>

我稍后在文档里追加一个说明吧，多谢反馈！ 😄
