### ISSUE TITLE
无线连接命令

### ISSUE THREAD

**Issue by pzxbc** [mzlogin/awesome-adb#26]
谢谢这么全的指引！ 

我在参考无线连接（需要root权限）一节指引中发现下面步骤有缺失

> 3. 打开 Android 设备上的终端模拟器，在里面依次运行命令：
> ```
> su
> setprop service.adb.tcp.port 5555
> ```

设置端口后还需要重启adbd服务
``` 
stop adbd
start adbd
```

**Comment by mzlogin** [comment]
感谢说明。

我用手上的 Nexus 5 试了一下，不重启 adbd 也是可以连上的。

那这个可能跟 ROM 有关吧，我稍到补充一个备注到文档里去，多谢！

**Comment by pzxbc** [comment]
@mzlogin 估计是。我的手机是小米5s，Rom是MIUI 8.0，Android版本是6.0.1MXB48T

**Comment by mzlogin** [comment]
添加了备注到文档里，多谢啦！
