### ISSUE TITLE
7.0上截图的问题

### ISSUE THREAD

**Issue by chenyue404** [mzlogin/awesome-adb#33]
不是文档的bug，就是讨论一下。

在三星S6，Android 7.0上，直接
adb shell screencap -p | sed "s/\r$//" > sc.png
会失败，文件可以创建，但是打不开图片，文件大小也是有的。
先adb shell screencap -p /sdcard/sc.png，再adb pull /sdcard/sc.png就没问题。

**Comment by mzlogin** [comment]
请问你的电脑操作系统是什么？在同样的环境下对其它 Android 版本执行该命令的结果如何呢？

**Comment by chenyue404** [comment]
抱歉忘了说了，电脑是win10 64位，其他版本的Android没有出现问题。实际上是上次把S6升级到7.0之后才出现此问题，没升级之前是正常的。我待会拿个别的7.0的手机试试。

**Comment by chenyue404** [comment]
刚试了下。好像是我电脑问题……

**Comment by chenyue404** [comment]
但是试了其他版本的adb都是这样啊，可能是什么问题呢？sed命令的问题？

**Comment by mzlogin** [comment]
我大致看了一下，对 Android 7.0 截图用 `adb shell screencap -p | sed "s/\r$//" > sc.png` 处理完后，需要在第一行尾加一个 `\r` 才是有效的 png 格式文件。

Android 6.0 上 `adb shell screencap -p` 的输出第一行是 `8950 4e47 0d0d 0d0a`，而 Android 7.0 输出第一行是 `8950 4e47 0d0d 0a`，少了一个 `0d`，容我想想解决办法，你也帮忙想想，多谢！

**Comment by chenyue404** [comment]
额，这里的输出是怎么看的？哪里的输出？

**Comment by mzlogin** [comment]
把命令的输出重定向到文本文件，比如 `adb shell screencap -p > 1.txt`，然后将文件作为十六进制文件打开看。

**Comment by chenyue404** [comment]
嗯，还发现一个问题，我用的win10，同样的命令，用powershell执行就不行，不管手机是什么版本，cmd+6.0就可以，7.0不行。
![image](https://cloud.githubusercontent.com/assets/5474422/25831211/f89d70c4-3494-11e7-96e6-8779bc227201.png)

**Comment by chenyue404** [comment]
sed命令问题，windows下可以用adb exec-out screencap -p > test.png解决

**Comment by mzlogin** [comment]
还真是~adb 的 help 输出里居然完全没提到 exec-out，感谢~回头我试试 Linux 和 Mac 下能不能这么用，如果也可以就太好了。

**Comment by mzlogin** [comment]
https://github.com/android/platform_system_core/commit/5d9d434efadf1c535c7fea634d5306e18c68ef1f

2014-5-27 的一次提交就已经添加了 exec-out 的支持，我在 Mac 下试了也好使，看来只要不是特别老版本的 adb 应该都可用了，我去更新下文档。 :)

**Comment by iflove** [comment]
感谢~
