### ISSUE TITLE
adb install更详细的用法

### ISSUE THREAD

**Issue by codeskyblue** [mzlogin/awesome-adb#5]
写的稍微有点乱，lz自己整理下。

adb install 1.0.36会出现安装进度。

adb install的过程：

1. push文件到/data/local/tmp
2. 调用pm install安装软件

缺点，目前的adb install不会删除到残留在/data/local/tmp下的安装包

手动安装方法

1. `adb push some.apk /data/local/tmp/`
1. `adb shell pm install /data/local/tmp/some.apk`
2. 清理 `adb shell rm /data/local/tmp/some.apk`

BTW: adb在mac上还有更好的实现 <https://github.com/facebook/fb-adb>

**Comment by mzlogin** [comment]
收到~我回头整理补充一下，感谢！ @codeskyblue

**Comment by mzlogin** [comment]
已经整理补充了一下，还觉得有问题的地方也请再次指出。

我这边实测 adb 1.0.36 在 5.1.1 和 6.0 上 install 的时候会删除 /data/local/tmp 下的文件。

**Comment by codeskyblue** [comment]
nice
