### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by myzcl** [mzlogin/awesome-adb#54]
我测试了一下，点击屏幕用时1s左右，截图就需要4s，感觉速度太慢，一些实时性的游戏就适应不了，adb能不能再快一点呢？

**Comment by mzlogin** [comment]
我这边试的话，用 adb 命令截图 2S 多吧，点击 1S 以内吧。

实时性的游戏确实适应不了，我以前试过用网易的自动化测试框架 [ATX](https://github.com/NetEaseGame/ATX)，配合 [minicap](https://github.com/NetEaseGame/ATX/wiki/Command-Line-Tools)，能将截图时间缩短到 1S 以内，玩玩回合制游戏阴阳师一类的够用了，比如我和以前同事合作的 [yyhelper](https://github.com/gitzxon/yyhelper)。

实时性游戏的话，截图的思路我觉得不太适合，走内存分析，截包一类的路子可能靠谱点。

**Comment by mzlogin** [comment]
不客气~有新思路欢迎随时交流~
