### ISSUE TITLE
查看前台 Activity无效

### ISSUE THREAD

**Issue by micstart** [mzlogin/awesome-adb#59]
https://github.com/mzlogin/awesome-adb#%E6%9F%A5%E7%9C%8B%E5%89%8D%E5%8F%B0-activity
首选命令写的有问题，在window控制台中无法执行，需修改为：
adb shell "dumpsys activity activities | grep mFocusedActivity"
另外新的Android中dumpsys activity activities的输出中已经无法通过focuse关键字定位前台Activity了，可修改为：
adb shell "dumpsys activity activities | grep Run #"

**Comment by yuruiyin** [comment]
adb -d shell dumpsys activity activities | grep mResumedActivity
试试这个

**Comment by DeveloperZhuG** [comment]
adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp' --color=always

**Comment by mzlogin** [comment]
大家的意见已经合入，谢谢！
我测试在 Android 7、8、9 上使用 mResumedActivity 都能行，然后 Windows 下使用 findstr 替代 grep，或者将 shell 命令部分用双引号括起来都可以。
