### ISSUE TITLE
安装 adbd Insecure只有一个弹框，点击后闪退

### ISSUE THREAD

**Issue by ziyonghong** [mzlogin/awesome-adb#69]
安装 adbd Insecure后进入，弹框“ adbd Insecure  SuperUser access is needed,but could not be acquired.Are you rooted and did you give permission?” 然后只有“OK”可以点，点“OK”后就闪退了。而且下了root大师，也一键root失败，该怎么解决？

**Comment by mzlogin** [comment]
adbd insecure 是先 root，遇到文中提到的问题后才使用的，手机 root 了吗？还没有的话先想办法 root。

**Comment by ziyonghong** [comment]
好的，谢谢。但手机root失败，我再找找其他办法root吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhuang Ma"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 中午1:22
收件人:&nbsp;"mzlogin/awesome-adb"<awesome-adb@noreply.github.com&gt;;
抄送:&nbsp;"自永红"<1131002466@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mzlogin/awesome-adb] 安装 adbd Insecure只有一个弹框，点击后闪退 (#69)




adbd insecure 是先 root，遇到文中提到的问题后才使用的，手机 root 了吗？还没有的话先想办法 root。
