### ISSUE TITLE
时间设置不对

### ISSUE THREAD

**Issue by feiyangwei** [mzlogin/awesome-adb#72]
执行date -s 时一直提示unknown option s
可以用下边方式：
date MMDDhhmmYY.ss set
date 月日小时分钟年.秒 set
示例：
20191230120000
date 123012002019.00 set
亲测可用

**Comment by mzlogin** [comment]
那应该是不同的 ROM 集成的 date 命令版本不一样，Linux 下的 date 命令是支持 -s 选项的，参考 http://man7.org/linux/man-pages/man1/date.1.html

**Comment by feiyangwei** [comment]
晓得了，可能我这个系统中没有这个命令
