### ISSUE TITLE
请问知道如何通过 adb 打开 USB 网络共享

### ISSUE THREAD

**Issue by bananaCaptain** [mzlogin/awesome-adb#75]
请问知道如何通过 adb 打开 USB 网络共享 谢谢
 adb enable usb tethering

**Comment by bananaCaptain** [comment]
找到答案了，感谢
adb shell getprop sys.usb.config

adb shell setprop sys.usb.config rndis,adb

**Comment by mzlogin** [comment]
👍 抱歉没及时回应，这个我稍后也补充进文档里。感谢
