### ISSUE TITLE
screencap use sed Image error

### ISSUE THREAD

**Issue by 15922660642** [mzlogin/awesome-adb#78]
在执行 adb shell screencap -p | sed "s/\r$//" > sc.png的时候保存的图片是一张错误的图片
通过截图到手机再导出发现了图片里的\n仍然翻译成了\r\n导致图片错误,想问一下楼主这个问题应该怎么处理

**Comment by mzlogin** [comment]
> 在执行 adb shell screencap -p | sed "s/\r$//" > sc.png的时候保存的图片是一张错误的图片
> 通过截图到手机再导出发现了图片里的\n仍然翻译成了\r\n导致图片错误,想问一下楼主这个问题应该怎么处理

操作系统、adb 版本可以发算来看看么？

1. 试过 `adb exec-out screencap -p > sc.png` 没有呢？
2. 你说的“通过截图到手机再导出”，这里具体用的命令发出来看一下
3. 如果确定问题就是 `\n` 和 `\r\n` 的问题，你可以在电脑上使用 sed 处理

**Comment by 15922660642** [comment]
我使用的window 10,android 9 华为nov3
1.使用adb exec-out screencap -p > sc.png可以得到正常的截图
2.使用截图到手机指的是adb shell screencap -p sdcard/screen.png && adb pull sdcard/screen.png C:\Users\hzjy\Desktop合并操作的方式
3.确定是\n和\r\n的问题,但是使用在使用sed的时候并没有处理到对应的地方去
![这是通过adb shell screencap -p sdcard/screen.png && adb pull sdcard/screen.png C:\Users\hzjy\Desktop指令得到的正常图片](https://user-images.githubusercontent.com/16870825/96389433-2ec6e580-11e2-11eb-9d76-beaa6de9e850.png)
![这是通过adb shell screencap -p | sed "s/\r$//" > sc.png得到的错误图片](https://user-images.githubusercontent.com/16870825/96389460-4ef6a480-11e2-11eb-8d8a-eb5c1b2cf872.png)
在使用sed的添加了双引号,不然无法识别到sed操作指令
![1603066285(1)](https://user-images.githubusercontent.com/16870825/96389562-c7f5fc00-11e2-11eb-9c7b-82f43998005f.jpg)

**Comment by mzlogin** [comment]
> 我使用的window 10,android 9 华为nov3
> 1.使用adb exec-out screencap -p > sc.png可以得到正常的截图
> 2.使用截图到手机指的是adb shell screencap -p sdcard/screen.png && adb pull sdcard/screen.png C:\Users\hzjy\Desktop合并操作的方式
> 3.确定是\n和\r\n的问题,但是使用在使用sed的时候并没有处理到对应的地方去
> ![这是通过adb shell screencap -p sdcard/screen.png && adb pull sdcard/screen.png C:\Users\hzjy\Desktop指令得到的正常图片](https://user-images.githubusercontent.com/16870825/96389433-2ec6e580-11e2-11eb-9d76-beaa6de9e850.png)
> ![这是通过adb shell screencap -p | sed "s/\r$//" > sc.png得到的错误图片](https://user-images.githubusercontent.com/16870825/96389460-4ef6a480-11e2-11eb-8d8a-eb5c1b2cf872.png)
> 在使用sed的添加了双引号,不然无法识别到sed操作指令
> ![1603066285(1)](https://user-images.githubusercontent.com/16870825/96389562-c7f5fc00-11e2-11eb-9c7b-82f43998005f.jpg)

今天梯子不正常，图片下不下来……看不到情况。那就不纠缠它了吧，就用第一条命令 😆

**Comment by 15922660642** [comment]
好吧,谢谢您的解答

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/96414790-29888b80-1220-11eb-8b38-9f5f31e551c8.png)

我试了下，在 Mac 下用 gnu sed 处理成功啦……命令应该没问题，怀疑是与 Windows 下的 sed 的版本差异。
