### ISSUE TITLE
adb的无线连接的前提

### ISSUE THREAD

**Issue by seasonyuu** [mzlogin/awesome-adb#8]
刚看了另一个issue说 5.0以下的设备可以直接adb connect，但是在5.0以上不太一样，需要设备上执行过`setprop service.adb.tcp.port 5555` 之后重启adbd然后PC端才可以连接

**Comment by seasonyuu** [comment]
执行`setprop service.adb.tcp.port 5555`也可以通过adb shell来做

**Comment by mzlogin** [comment]
我猜你说的是 #4 ，那个 Issue 里讨论的是多台电脑连接同一个 Android 设备。如果只是一台电脑连接某 Android 设备的话，那我这边测试的情况是 5.0 以上的也可以在 `adb tcpip 5555` 后 `adb connect <ip-address>`。

`adb shell setprop service.adb.tcp.port 5555` 这个应该是与 `adb tcpip 5555` 类似的作用吧？在 Nexus 5 （Android 5.1.1）上执行 `setprop` 后能 `adb connect` 成功，在一个别的 6.0 的机器上未成功。

**Comment by seasonyuu** [comment]
`adb tcpip 5555` 应该只是指定PC端这边向手机连接的端口而已。我在什么设备上不用`setprop`都不能连接成，会提示连接被拒

**Comment by seasonyuu** [comment]
还有  这段`setprop`也要`su`

**Comment by mzlogin** [comment]
那看来还跟设备和 ROM 有关系，我用的 Nexus 5 没有 su 执行 setprop 也可以。

官方文档对无线连接步骤里 `adb tcpip 5555` 这一步的说明是 `Set the target device to listen for a TCP/IP connection on port 5555.`，所以它是会更改 adbd 的监听端口的。

**Comment by seasonyuu** [comment]
我setprop是在手机的终端执行的  AOSP

2016年8月31日 12:35，"Zhuang Ma" <notifications@github.com>写道：

**Comment by seasonyuu** [comment]
也主要是我觉得要用到这种模式就是要脱离数据线  所以没想到adb来执行设置监听端口

2016年8月31日 16:48，"Season Yuu" <seasonyuu@gmail.com>写道：

**Comment by mzlogin** [comment]
原来如此~了解了，你这个思路很赞。 :+1: 

我后来也尝试一下整理进文档，多谢！

**Comment by mzlogin** [comment]
我今天试验了你的方法方法，非常方便。

整理了之后加了一个小节「无线连接（无需借助 USB 线）」进去了，非常感谢你的分享！
