### ISSUE TITLE
请问Table of Contents是怎样生成的呢？

### ISSUE THREAD

**Issue by smyhvae** [mzlogin/awesome-adb#9]
如题

**Comment by mzlogin** [comment]
我使用 Vim 编辑 Markdown 文档，生成 Table of Contents 是用我自己做的一个插件：

<https://github.com/mzlogin/vim-markdown-toc>

安装好之后，编辑 Markdown 文档时将光标放在需要插入 Table of Contents 的地方，运行 `:GenTocGFM` 即可生成适用于 GitHub 的 ToC。
